// Code generated by goctl. DO NOT EDIT.
package types

type UserFile struct {
	Id                 int64  `json:"id"`
	Name               string `json:"name"`
	RepositoryIdentity string `json:"repositoryIdentity"`
	Identity           string `json:"identity"`
	Ext                string `json:"ext"`
	Path               string `json:"path"`
}

type Result struct {
	Code    int         `json:"code"`
	Data    interface{} `json:"data"`
	Message string      `json:"message"`
}

type LoginRequest struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Result
}

type RegisterRequest struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Code     string `json:"code"`
}

type RegisterResponse struct {
	Result
}

type GetCodeRequest struct {
	Email string `json:"email"` //用户邮箱
}

type GetCodeResponse struct {
	Result
}

type UserInfoRequest struct {
}

type UserInfoResponse struct {
	Result
}

type UploadFileRequest struct {
	Hash string `json:"hash,optional"`
	Name string `json:"name,optional"`
	Ext  string `json:"ext,optional"`
	Size int64  `json:"size,optional"`
	Path string `json:"path,optional"`
}

type UploadFileResponse struct {
	Result
}

type UserRepositoryLinkRequest struct {
	ParentId           int64  `json:"parentId"`
	RepositoryIdentity string `json:"repositoryIdentity"`
	Ext                string `json:"ext"`
	Name               string `json:"name"`
}

type UserRepositoryLinkResponse struct {
	Result
}

type UserFileListRequest struct {
	Id   int64 `json:"id,optional"`
	Page int   `json:"page,optional"`
	Size int   `json:"size,optional"`
}

type UserFileListResponse struct {
	Result
}
